// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kafka.consumer.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer;

/**
 * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap}
 */
public final class KafkaConsumersMap extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap)
    KafkaConsumersMapOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      KafkaConsumersMap.class.getName());
  }
  // Use KafkaConsumersMap.newBuilder() to construct.
  private KafkaConsumersMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private KafkaConsumersMap() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_KafkaConsumersMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetConsumers();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_KafkaConsumersMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap.class, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap.Builder.class);
  }

  public static final int CONSUMERS_FIELD_NUMBER = 1;
  private static final class ConsumersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer>newDefaultInstance(
                io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_KafkaConsumersMap_ConsumersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> consumers_;
  private com.google.protobuf.MapField<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer>
  internalGetConsumers() {
    if (consumers_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ConsumersDefaultEntryHolder.defaultEntry);
    }
    return consumers_;
  }
  public int getConsumersCount() {
    return internalGetConsumers().getMap().size();
  }
  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  @java.lang.Override
  public boolean containsConsumers(
      int key) {

    return internalGetConsumers().getMap().containsKey(key);
  }
  /**
   * Use {@link #getConsumersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> getConsumers() {
    return getConsumersMap();
  }
  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> getConsumersMap() {
    return internalGetConsumers().getMap();
  }
  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer getConsumersOrDefault(
      int key,
      /* nullable */
io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer defaultValue) {

    java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> map =
        internalGetConsumers().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  @java.lang.Override
  public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer getConsumersOrThrow(
      int key) {

    java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> map =
        internalGetConsumers().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeIntegerMapTo(
        output,
        internalGetConsumers(),
        ConsumersDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> entry
         : internalGetConsumers().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer>
      consumers__ = ConsumersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, consumers__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap)) {
      return super.equals(obj);
    }
    io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap other = (io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap) obj;

    if (!internalGetConsumers().equals(
        other.internalGetConsumers())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetConsumers().getMap().isEmpty()) {
      hash = (37 * hash) + CONSUMERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetConsumers().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap)
      io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_KafkaConsumersMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetConsumers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableConsumers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_KafkaConsumersMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap.class, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap.Builder.class);
    }

    // Construct using io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableConsumers().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_KafkaConsumersMap_descriptor;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap getDefaultInstanceForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap build() {
      io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap buildPartial() {
      io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap result = new io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.consumers_ = internalGetConsumers().build(ConsumersDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap) {
        return mergeFrom((io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap other) {
      if (other == io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap.getDefaultInstance()) return this;
      internalGetMutableConsumers().mergeFrom(
          other.internalGetConsumers());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer>
              consumers__ = input.readMessage(
                  ConsumersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableConsumers().ensureBuilderMap().put(
                  consumers__.getKey(), consumers__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class ConsumersConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> {
      @java.lang.Override
      public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer build(io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder val) {
        if (val instanceof io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer) { return (io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer) val; }
        return ((io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> defaultEntry() {
        return ConsumersDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ConsumersConverter consumersConverter = new ConsumersConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer.Builder> consumers_;
    private com.google.protobuf.MapFieldBuilder<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer.Builder>
        internalGetConsumers() {
      if (consumers_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(consumersConverter);
      }
      return consumers_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer.Builder>
        internalGetMutableConsumers() {
      if (consumers_ == null) {
        consumers_ = new com.google.protobuf.MapFieldBuilder<>(consumersConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return consumers_;
    }
    public int getConsumersCount() {
      return internalGetConsumers().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
     */
    @java.lang.Override
    public boolean containsConsumers(
        int key) {

      return internalGetConsumers().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getConsumersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> getConsumers() {
      return getConsumersMap();
    }
    /**
     * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> getConsumersMap() {
      return internalGetConsumers().getImmutableMap();
    }
    /**
     * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer getConsumersOrDefault(
        int key,
        /* nullable */
io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer defaultValue) {

      java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder> map = internalGetMutableConsumers().ensureBuilderMap();
      return map.containsKey(key) ? consumersConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
     */
    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer getConsumersOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder> map = internalGetMutableConsumers().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return consumersConverter.build(map.get(key));
    }
    public Builder clearConsumers() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableConsumers().clear();
      return this;
    }
    /**
     * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
     */
    public Builder removeConsumers(
        int key) {

      internalGetMutableConsumers().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer>
        getMutableConsumers() {
      bitField0_ |= 0x00000001;
      return internalGetMutableConsumers().ensureMessageMap();
    }
    /**
     * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
     */
    public Builder putConsumers(
        int key,
        io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer value) {

      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableConsumers().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
     */
    public Builder putAllConsumers(
        java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> values) {
      for (java.util.Map.Entry<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableConsumers().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
     */
    public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer.Builder putConsumersBuilderIfAbsent(
        int key) {
      java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder> builderMap = internalGetMutableConsumers().ensureBuilderMap();
      io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer) {
        entry = ((io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap)
  }

  // @@protoc_insertion_point(class_scope:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap)
  private static final io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap();
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KafkaConsumersMap>
      PARSER = new com.google.protobuf.AbstractParser<KafkaConsumersMap>() {
    @java.lang.Override
    public KafkaConsumersMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<KafkaConsumersMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KafkaConsumersMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

