// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kafka.consumer.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer;

public interface KafkaConsumersMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumersMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  int getConsumersCount();
  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  boolean containsConsumers(
      int key);
  /**
   * Use {@link #getConsumersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer>
  getConsumers();
  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  java.util.Map<java.lang.Integer, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer>
  getConsumersMap();
  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  /* nullable */
io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer getConsumersOrDefault(
      int key,
      /* nullable */
io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer defaultValue);
  /**
   * <code>map&lt;int32, .io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer&gt; consumers = 1;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumer getConsumersOrThrow(
      int key);
}
