// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kafka.consumer.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer;

/**
 * Protobuf enum {@code io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerPartitionEventType}
 */
public enum KafkaConsumerPartitionEventType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>REVOKED = 0;</code>
   */
  REVOKED(0),
  /**
   * <code>ASSIGNED = 1;</code>
   */
  ASSIGNED(1),
  /**
   * <code>LOST = 2;</code>
   */
  LOST(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      KafkaConsumerPartitionEventType.class.getName());
  }
  /**
   * <code>REVOKED = 0;</code>
   */
  public static final int REVOKED_VALUE = 0;
  /**
   * <code>ASSIGNED = 1;</code>
   */
  public static final int ASSIGNED_VALUE = 1;
  /**
   * <code>LOST = 2;</code>
   */
  public static final int LOST_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static KafkaConsumerPartitionEventType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static KafkaConsumerPartitionEventType forNumber(int value) {
    switch (value) {
      case 0: return REVOKED;
      case 1: return ASSIGNED;
      case 2: return LOST;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<KafkaConsumerPartitionEventType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      KafkaConsumerPartitionEventType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<KafkaConsumerPartitionEventType>() {
          public KafkaConsumerPartitionEventType findValueByNumber(int number) {
            return KafkaConsumerPartitionEventType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final KafkaConsumerPartitionEventType[] VALUES = values();

  public static KafkaConsumerPartitionEventType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private KafkaConsumerPartitionEventType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerPartitionEventType)
}

