// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kafka.consumer.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer;

public interface KafkaConsumerStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 commits = 1;</code>
   * @return The commits.
   */
  int getCommits();

  /**
   * <code>int32 commited = 2;</code>
   * @return The commited.
   */
  int getCommited();

  /**
   * <code>int32 commitFailed = 3;</code>
   * @return The commitFailed.
   */
  int getCommitFailed();

  /**
   * <code>int64 last_commit_at = 4;</code>
   * @return The lastCommitAt.
   */
  long getLastCommitAt();
}
