// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kafka.consumer.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer;

/**
 * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets}
 */
public final class PartitionOffsets extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets)
    PartitionOffsetsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PartitionOffsets.class.getName());
  }
  // Use PartitionOffsets.newBuilder() to construct.
  private PartitionOffsets(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PartitionOffsets() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_PartitionOffsets_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_PartitionOffsets_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets.class, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets.Builder.class);
  }

  public static final int CURRENT_OFFSET_FIELD_NUMBER = 1;
  private long currentOffset_ = 0L;
  /**
   * <code>int64 current_offset = 1;</code>
   * @return The currentOffset.
   */
  @java.lang.Override
  public long getCurrentOffset() {
    return currentOffset_;
  }

  public static final int LAST_COMMIT_FIELD_NUMBER = 2;
  private long lastCommit_ = 0L;
  /**
   * <code>int64 last_commit = 2;</code>
   * @return The lastCommit.
   */
  @java.lang.Override
  public long getLastCommit() {
    return lastCommit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentOffset_ != 0L) {
      output.writeInt64(1, currentOffset_);
    }
    if (lastCommit_ != 0L) {
      output.writeInt64(2, lastCommit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, currentOffset_);
    }
    if (lastCommit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, lastCommit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets)) {
      return super.equals(obj);
    }
    io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets other = (io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets) obj;

    if (getCurrentOffset()
        != other.getCurrentOffset()) return false;
    if (getLastCommit()
        != other.getLastCommit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENT_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentOffset());
    hash = (37 * hash) + LAST_COMMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastCommit());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets)
      io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsetsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_PartitionOffsets_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_PartitionOffsets_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets.class, io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets.Builder.class);
    }

    // Construct using io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      currentOffset_ = 0L;
      lastCommit_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.KafkaConsumerOuterClass.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_kafka_consumer_PartitionOffsets_descriptor;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets getDefaultInstanceForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets build() {
      io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets buildPartial() {
      io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets result = new io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.currentOffset_ = currentOffset_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lastCommit_ = lastCommit_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets) {
        return mergeFrom((io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets other) {
      if (other == io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets.getDefaultInstance()) return this;
      if (other.getCurrentOffset() != 0L) {
        setCurrentOffset(other.getCurrentOffset());
      }
      if (other.getLastCommit() != 0L) {
        setLastCommit(other.getLastCommit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              currentOffset_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              lastCommit_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long currentOffset_ ;
    /**
     * <code>int64 current_offset = 1;</code>
     * @return The currentOffset.
     */
    @java.lang.Override
    public long getCurrentOffset() {
      return currentOffset_;
    }
    /**
     * <code>int64 current_offset = 1;</code>
     * @param value The currentOffset to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentOffset(long value) {

      currentOffset_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 current_offset = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentOffset() {
      bitField0_ = (bitField0_ & ~0x00000001);
      currentOffset_ = 0L;
      onChanged();
      return this;
    }

    private long lastCommit_ ;
    /**
     * <code>int64 last_commit = 2;</code>
     * @return The lastCommit.
     */
    @java.lang.Override
    public long getLastCommit() {
      return lastCommit_;
    }
    /**
     * <code>int64 last_commit = 2;</code>
     * @param value The lastCommit to set.
     * @return This builder for chaining.
     */
    public Builder setLastCommit(long value) {

      lastCommit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_commit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCommit() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lastCommit_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets)
  }

  // @@protoc_insertion_point(class_scope:io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets)
  private static final io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets();
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PartitionOffsets>
      PARSER = new com.google.protobuf.AbstractParser<PartitionOffsets>() {
    @java.lang.Override
    public PartitionOffsets parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PartitionOffsets> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PartitionOffsets> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.sibmaks.spring.jfr.dto.protobuf.kafka.consumer.PartitionOffsets getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

