// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connections.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.connections;

public interface ConnectionEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 index = 1;</code>
   * @return The index.
   */
  long getIndex();

  /**
   * <code>int64 action = 2;</code>
   * @return The action.
   */
  long getAction();

  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionException exception = 3;</code>
   * @return Whether the exception field is set.
   */
  boolean hasException();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionException exception = 3;</code>
   * @return The exception.
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionException getException();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionException exception = 3;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionExceptionOrBuilder getExceptionOrBuilder();

  /**
   * <code>int64 started_at = 4;</code>
   * @return The startedAt.
   */
  long getStartedAt();

  /**
   * <code>int64 finished_at = 5;</code>
   * @return The finishedAt.
   */
  long getFinishedAt();

  /**
   * <code>int32 thread_name = 6;</code>
   * @return The threadName.
   */
  int getThreadName();

  /**
   * <code>optional int32 transaction_isolation = 7;</code>
   * @return Whether the transactionIsolation field is set.
   */
  boolean hasTransactionIsolation();
  /**
   * <code>optional int32 transaction_isolation = 7;</code>
   * @return The transactionIsolation.
   */
  int getTransactionIsolation();
}
