// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connections.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.connections;

/**
 * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection}
 */
public final class Connection extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection)
    ConnectionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Connection.class.getName());
  }
  // Use Connection.newBuilder() to construct.
  private Connection(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Connection() {
    events_ = java.util.Collections.emptyList();
    id_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connections.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_connections_Connection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connections.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_connections_Connection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection.class, io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection.Builder.class);
  }

  public static final int EVENTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent> events_;
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent> getEventsList() {
    return events_;
  }
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder> 
      getEventsOrBuilderList() {
    return events_;
  }
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  @java.lang.Override
  public int getEventsCount() {
    return events_.size();
  }
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  @java.lang.Override
  public io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent getEvents(int index) {
    return events_.get(index);
  }
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  @java.lang.Override
  public io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder getEventsOrBuilder(
      int index) {
    return events_.get(index);
  }

  public static final int ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_FIELD_NUMBER = 3;
  private long duration_ = 0L;
  /**
   * <code>int64 duration = 3;</code>
   * @return The duration.
   */
  @java.lang.Override
  public long getDuration() {
    return duration_;
  }

  public static final int HAS_EXCEPTIONS_FIELD_NUMBER = 4;
  private boolean hasExceptions_ = false;
  /**
   * <code>bool has_exceptions = 4;</code>
   * @return The hasExceptions.
   */
  @java.lang.Override
  public boolean getHasExceptions() {
    return hasExceptions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < events_.size(); i++) {
      output.writeMessage(1, events_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, id_);
    }
    if (duration_ != 0L) {
      output.writeInt64(3, duration_);
    }
    if (hasExceptions_ != false) {
      output.writeBool(4, hasExceptions_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < events_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, events_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, id_);
    }
    if (duration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, duration_);
    }
    if (hasExceptions_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, hasExceptions_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection)) {
      return super.equals(obj);
    }
    io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection other = (io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection) obj;

    if (!getEventsList()
        .equals(other.getEventsList())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (getDuration()
        != other.getDuration()) return false;
    if (getHasExceptions()
        != other.getHasExceptions()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEventsCount() > 0) {
      hash = (37 * hash) + EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getEventsList().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDuration());
    hash = (37 * hash) + HAS_EXCEPTIONS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasExceptions());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection)
      io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connections.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_connections_Connection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connections.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_connections_Connection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection.class, io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection.Builder.class);
    }

    // Construct using io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
      } else {
        events_ = null;
        eventsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = "";
      duration_ = 0L;
      hasExceptions_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connections.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_connections_Connection_descriptor;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection getDefaultInstanceForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection build() {
      io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection buildPartial() {
      io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection result = new io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection result) {
      if (eventsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          events_ = java.util.Collections.unmodifiableList(events_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.events_ = events_;
      } else {
        result.events_ = eventsBuilder_.build();
      }
    }

    private void buildPartial0(io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.duration_ = duration_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hasExceptions_ = hasExceptions_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection) {
        return mergeFrom((io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection other) {
      if (other == io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection.getDefaultInstance()) return this;
      if (eventsBuilder_ == null) {
        if (!other.events_.isEmpty()) {
          if (events_.isEmpty()) {
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEventsIsMutable();
            events_.addAll(other.events_);
          }
          onChanged();
        }
      } else {
        if (!other.events_.isEmpty()) {
          if (eventsBuilder_.isEmpty()) {
            eventsBuilder_.dispose();
            eventsBuilder_ = null;
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000001);
            eventsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getEventsFieldBuilder() : null;
          } else {
            eventsBuilder_.addAllMessages(other.events_);
          }
        }
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getDuration() != 0L) {
        setDuration(other.getDuration());
      }
      if (other.getHasExceptions() != false) {
        setHasExceptions(other.getHasExceptions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent m =
                  input.readMessage(
                      io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.parser(),
                      extensionRegistry);
              if (eventsBuilder_ == null) {
                ensureEventsIsMutable();
                events_.add(m);
              } else {
                eventsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              duration_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              hasExceptions_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent> events_ =
      java.util.Collections.emptyList();
    private void ensureEventsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        events_ = new java.util.ArrayList<io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent>(events_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder> eventsBuilder_;

    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public java.util.List<io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent> getEventsList() {
      if (eventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(events_);
      } else {
        return eventsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public int getEventsCount() {
      if (eventsBuilder_ == null) {
        return events_.size();
      } else {
        return eventsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent getEvents(int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);
      } else {
        return eventsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder setEvents(
        int index, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.set(index, value);
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder setEvents(
        int index, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.set(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder addEvents(io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder addEvents(
        int index, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(index, value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder addEvents(
        io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder addEvents(
        int index, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder addAllEvents(
        java.lang.Iterable<? extends io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent> values) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, events_);
        onChanged();
      } else {
        eventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder clearEvents() {
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        eventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public Builder removeEvents(int index) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.remove(index);
        onChanged();
      } else {
        eventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder getEventsBuilder(
        int index) {
      return getEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder getEventsOrBuilder(
        int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);  } else {
        return eventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public java.util.List<? extends io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder> 
         getEventsOrBuilderList() {
      if (eventsBuilder_ != null) {
        return eventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(events_);
      }
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder addEventsBuilder() {
      return getEventsFieldBuilder().addBuilder(
          io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder addEventsBuilder(
        int index) {
      return getEventsFieldBuilder().addBuilder(
          index, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
     */
    public java.util.List<io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder> 
         getEventsBuilderList() {
      return getEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder> 
        getEventsFieldBuilder() {
      if (eventsBuilder_ == null) {
        eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent.Builder, io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder>(
                events_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        events_ = null;
      }
      return eventsBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long duration_ ;
    /**
     * <code>int64 duration = 3;</code>
     * @return The duration.
     */
    @java.lang.Override
    public long getDuration() {
      return duration_;
    }
    /**
     * <code>int64 duration = 3;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(long value) {

      duration_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 duration = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000004);
      duration_ = 0L;
      onChanged();
      return this;
    }

    private boolean hasExceptions_ ;
    /**
     * <code>bool has_exceptions = 4;</code>
     * @return The hasExceptions.
     */
    @java.lang.Override
    public boolean getHasExceptions() {
      return hasExceptions_;
    }
    /**
     * <code>bool has_exceptions = 4;</code>
     * @param value The hasExceptions to set.
     * @return This builder for chaining.
     */
    public Builder setHasExceptions(boolean value) {

      hasExceptions_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_exceptions = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasExceptions() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hasExceptions_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection)
  }

  // @@protoc_insertion_point(class_scope:io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection)
  private static final io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection();
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Connection>
      PARSER = new com.google.protobuf.AbstractParser<Connection>() {
    @java.lang.Override
    public Connection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Connection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Connection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

