// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connections.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.connections;

public interface ConnectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  java.util.List<io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent> 
      getEventsList();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent getEvents(int index);
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  java.util.List<? extends io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEvent events = 1;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionEventOrBuilder getEventsOrBuilder(
      int index);

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int64 duration = 3;</code>
   * @return The duration.
   */
  long getDuration();

  /**
   * <code>bool has_exceptions = 4;</code>
   * @return The hasExceptions.
   */
  boolean getHasExceptions();
}
