// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connections.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.connections;

public interface ConnectionExceptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionException)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 type = 1;</code>
   * @return The type.
   */
  long getType();

  /**
   * <code>int64 message = 2;</code>
   * @return The message.
   */
  long getMessage();
}
