[versions]
spring-jfr-api = "0.0.8"

lombok = "1.18.34"
thymeleaf = "3.1.2.RELEASE"
junit-jupiter = "5.10.3"

[libraries]

spring-jfr-api = { module = "io.github.sibmaks.spring-jfr:api", version.ref = "spring-jfr-api" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
