// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calls.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.calls;

public interface CallTraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 invocation_id = 1;</code>
   * @return The invocationId.
   */
  int getInvocationId();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int32 type = 3;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>int64 start_time = 4;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 5;</code>
   * @return The endTime.
   */
  long getEndTime();

  /**
   * <code>int32 thread_name = 6;</code>
   * @return The threadName.
   */
  int getThreadName();

  /**
   * <code>int32 class_name = 7;</code>
   * @return The className.
   */
  int getClassName();

  /**
   * <code>int32 method_name = 8;</code>
   * @return The methodName.
   */
  int getMethodName();

  /**
   * <code>map&lt;int32, int32&gt; details = 9;</code>
   */
  int getDetailsCount();
  /**
   * <code>map&lt;int32, int32&gt; details = 9;</code>
   */
  boolean containsDetails(
      int key);
  /**
   * Use {@link #getDetailsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getDetails();
  /**
   * <code>map&lt;int32, int32&gt; details = 9;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getDetailsMap();
  /**
   * <code>map&lt;int32, int32&gt; details = 9;</code>
   */
  int getDetailsOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; details = 9;</code>
   */
  int getDetailsOrThrow(
      int key);

  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace children = 10;</code>
   */
  java.util.List<io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace> 
      getChildrenList();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace children = 10;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace getChildren(int index);
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace children = 10;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace children = 10;</code>
   */
  java.util.List<? extends io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace children = 10;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceOrBuilder getChildrenOrBuilder(
      int index);
}
