// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calls.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.calls;

public interface CallsReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallsReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int64, .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList&gt; contexts = 1;</code>
   */
  int getContextsCount();
  /**
   * <code>map&lt;int64, .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList&gt; contexts = 1;</code>
   */
  boolean containsContexts(
      long key);
  /**
   * Use {@link #getContextsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList>
  getContexts();
  /**
   * <code>map&lt;int64, .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList&gt; contexts = 1;</code>
   */
  java.util.Map<java.lang.Long, io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList>
  getContextsMap();
  /**
   * <code>map&lt;int64, .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList&gt; contexts = 1;</code>
   */
  /* nullable */
io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList getContextsOrDefault(
      long key,
      /* nullable */
io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList defaultValue);
  /**
   * <code>map&lt;int64, .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList&gt; contexts = 1;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList getContextsOrThrow(
      long key);
}
