// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calls.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.calls;

public final class Calls {
  private Calls() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Calls.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_DetailsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTraceList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTraceList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_ContextsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_ContextsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013calls.proto\022/io.github.sibmaks.spring." +
      "jfr.dto.protobuf.calls\"\375\002\n\tCallTrace\022\025\n\r" +
      "invocation_id\030\001 \001(\003\022\017\n\007success\030\002 \001(\005\022\014\n\004" +
      "type\030\003 \001(\003\022\022\n\nstart_time\030\004 \001(\003\022\020\n\010end_ti" +
      "me\030\005 \001(\003\022\023\n\013thread_name\030\006 \001(\003\022\022\n\nclass_n" +
      "ame\030\007 \001(\003\022\023\n\013method_name\030\010 \001(\003\022X\n\007detail" +
      "s\030\t \003(\0132G.io.github.sibmaks.spring.jfr.d" +
      "to.protobuf.calls.CallTrace.DetailsEntry" +
      "\022L\n\010children\030\n \003(\0132:.io.github.sibmaks.s" +
      "pring.jfr.dto.protobuf.calls.CallTrace\032." +
      "\n\014DetailsEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001" +
      "(\003:\0028\001\"`\n\rCallTraceList\022O\n\013call_traces\030\001" +
      " \003(\0132:.io.github.sibmaks.spring.jfr.dto." +
      "protobuf.calls.CallTrace\"\334\001\n\013CallsReport" +
      "\022\\\n\010contexts\030\001 \003(\0132J.io.github.sibmaks.s" +
      "pring.jfr.dto.protobuf.calls.CallsReport" +
      ".ContextsEntry\032o\n\rContextsEntry\022\013\n\003key\030\001" +
      " \001(\003\022M\n\005value\030\002 \001(\0132>.io.github.sibmaks." +
      "spring.jfr.dto.protobuf.calls.CallTraceL" +
      "ist:\0028\001B3\n/io.github.sibmaks.spring.jfr." +
      "dto.protobuf.callsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_descriptor,
        new java.lang.String[] { "InvocationId", "Success", "Type", "StartTime", "EndTime", "ThreadName", "ClassName", "MethodName", "Details", "Children", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_DetailsEntry_descriptor =
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_descriptor.getNestedTypes().get(0);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTrace_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTraceList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTraceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallTraceList_descriptor,
        new java.lang.String[] { "CallTraces", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_descriptor,
        new java.lang.String[] { "Contexts", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_ContextsEntry_descriptor =
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_descriptor.getNestedTypes().get(0);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_ContextsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_calls_CallsReport_ContextsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
