// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calls.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.calls;

public interface CallTraceListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace call_traces = 1;</code>
   */
  java.util.List<io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace> 
      getCallTracesList();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace call_traces = 1;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace getCallTraces(int index);
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace call_traces = 1;</code>
   */
  int getCallTracesCount();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace call_traces = 1;</code>
   */
  java.util.List<? extends io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceOrBuilder> 
      getCallTracesOrBuilderList();
  /**
   * <code>repeated .io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTrace call_traces = 1;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallTraceOrBuilder getCallTracesOrBuilder(
      int index);
}
