// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.common;

/**
 * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto}
 */
public final class CommonDto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto)
    CommonDtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      CommonDto.class.getName());
  }
  // Use CommonDto.newBuilder() to construct.
  private CommonDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CommonDto() {
    stringConstants_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.common.Common.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.common.Common.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto.class, io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto.Builder.class);
  }

  public static final int STRING_CONSTANTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList stringConstants_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string string_constants = 1;</code>
   * @return A list containing the stringConstants.
   */
  public com.google.protobuf.ProtocolStringList
      getStringConstantsList() {
    return stringConstants_;
  }
  /**
   * <code>repeated string string_constants = 1;</code>
   * @return The count of stringConstants.
   */
  public int getStringConstantsCount() {
    return stringConstants_.size();
  }
  /**
   * <code>repeated string string_constants = 1;</code>
   * @param index The index of the element to return.
   * @return The stringConstants at the given index.
   */
  public java.lang.String getStringConstants(int index) {
    return stringConstants_.get(index);
  }
  /**
   * <code>repeated string string_constants = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stringConstants at the given index.
   */
  public com.google.protobuf.ByteString
      getStringConstantsBytes(int index) {
    return stringConstants_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < stringConstants_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, stringConstants_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < stringConstants_.size(); i++) {
        dataSize += computeStringSizeNoTag(stringConstants_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStringConstantsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto)) {
      return super.equals(obj);
    }
    io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto other = (io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto) obj;

    if (!getStringConstantsList()
        .equals(other.getStringConstantsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStringConstantsCount() > 0) {
      hash = (37 * hash) + STRING_CONSTANTS_FIELD_NUMBER;
      hash = (53 * hash) + getStringConstantsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto)
      io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.common.Common.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.common.Common.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto.class, io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto.Builder.class);
    }

    // Construct using io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      stringConstants_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.common.Common.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_descriptor;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto getDefaultInstanceForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto build() {
      io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto buildPartial() {
      io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto result = new io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        stringConstants_.makeImmutable();
        result.stringConstants_ = stringConstants_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto) {
        return mergeFrom((io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto other) {
      if (other == io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto.getDefaultInstance()) return this;
      if (!other.stringConstants_.isEmpty()) {
        if (stringConstants_.isEmpty()) {
          stringConstants_ = other.stringConstants_;
          bitField0_ |= 0x00000001;
        } else {
          ensureStringConstantsIsMutable();
          stringConstants_.addAll(other.stringConstants_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureStringConstantsIsMutable();
              stringConstants_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList stringConstants_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureStringConstantsIsMutable() {
      if (!stringConstants_.isModifiable()) {
        stringConstants_ = new com.google.protobuf.LazyStringArrayList(stringConstants_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @return A list containing the stringConstants.
     */
    public com.google.protobuf.ProtocolStringList
        getStringConstantsList() {
      stringConstants_.makeImmutable();
      return stringConstants_;
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @return The count of stringConstants.
     */
    public int getStringConstantsCount() {
      return stringConstants_.size();
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @param index The index of the element to return.
     * @return The stringConstants at the given index.
     */
    public java.lang.String getStringConstants(int index) {
      return stringConstants_.get(index);
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stringConstants at the given index.
     */
    public com.google.protobuf.ByteString
        getStringConstantsBytes(int index) {
      return stringConstants_.getByteString(index);
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @param index The index to set the value at.
     * @param value The stringConstants to set.
     * @return This builder for chaining.
     */
    public Builder setStringConstants(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStringConstantsIsMutable();
      stringConstants_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @param value The stringConstants to add.
     * @return This builder for chaining.
     */
    public Builder addStringConstants(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStringConstantsIsMutable();
      stringConstants_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @param values The stringConstants to add.
     * @return This builder for chaining.
     */
    public Builder addAllStringConstants(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringConstantsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stringConstants_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringConstants() {
      stringConstants_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_constants = 1;</code>
     * @param value The bytes of the stringConstants to add.
     * @return This builder for chaining.
     */
    public Builder addStringConstantsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureStringConstantsIsMutable();
      stringConstants_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto)
  }

  // @@protoc_insertion_point(class_scope:io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto)
  private static final io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto();
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommonDto>
      PARSER = new com.google.protobuf.AbstractParser<CommonDto>() {
    @java.lang.Override
    public CommonDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommonDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommonDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

