// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.common;

public final class Common {
  private Common() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Common.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_RootReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_RootReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\0220io.github.sibmaks.spring" +
      ".jfr.dto.protobuf.common\032\013beans.proto\032\013c" +
      "alls.proto\032\021connections.proto\"%\n\tCommonD" +
      "to\022\030\n\020string_constants\030\001 \003(\t\"\322\002\n\nRootRep" +
      "ort\022K\n\006common\030\001 \001(\0132;.io.github.sibmaks." +
      "spring.jfr.dto.protobuf.common.CommonDto" +
      "\022K\n\005beans\030\002 \001(\0132<.io.github.sibmaks.spri" +
      "ng.jfr.dto.protobuf.beans.BeansReport\022K\n" +
      "\005calls\030\003 \001(\0132<.io.github.sibmaks.spring." +
      "jfr.dto.protobuf.calls.CallsReport\022]\n\013co" +
      "nnections\030\004 \001(\0132H.io.github.sibmaks.spri" +
      "ng.jfr.dto.protobuf.connections.Connecti" +
      "onsReportB4\n0io.github.sibmaks.spring.jf" +
      "r.dto.protobuf.commonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.sibmaks.spring.jfr.dto.protobuf.beans.Beans.getDescriptor(),
          io.github.sibmaks.spring.jfr.dto.protobuf.calls.Calls.getDescriptor(),
          io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connections.getDescriptor(),
        });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_CommonDto_descriptor,
        new java.lang.String[] { "StringConstants", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_RootReport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_RootReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_common_RootReport_descriptor,
        new java.lang.String[] { "Common", "Beans", "Calls", "Connections", });
    descriptor.resolveAllFeaturesImmutable();
    io.github.sibmaks.spring.jfr.dto.protobuf.beans.Beans.getDescriptor();
    io.github.sibmaks.spring.jfr.dto.protobuf.calls.Calls.getDescriptor();
    io.github.sibmaks.spring.jfr.dto.protobuf.connections.Connections.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
