// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.common;

public interface RootReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.common.RootReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto common = 1;</code>
   * @return The common.
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto getCommon();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDto common = 1;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.common.CommonDtoOrBuilder getCommonOrBuilder();

  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeansReport beans = 2;</code>
   * @return Whether the beans field is set.
   */
  boolean hasBeans();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeansReport beans = 2;</code>
   * @return The beans.
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeansReport getBeans();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeansReport beans = 2;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeansReportOrBuilder getBeansOrBuilder();

  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallsReport calls = 3;</code>
   * @return Whether the calls field is set.
   */
  boolean hasCalls();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallsReport calls = 3;</code>
   * @return The calls.
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallsReport getCalls();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallsReport calls = 3;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.calls.CallsReportOrBuilder getCallsOrBuilder();

  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionsReport connections = 4;</code>
   * @return Whether the connections field is set.
   */
  boolean hasConnections();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionsReport connections = 4;</code>
   * @return The connections.
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionsReport getConnections();
  /**
   * <code>.io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionsReport connections = 4;</code>
   */
  io.github.sibmaks.spring.jfr.dto.protobuf.connections.ConnectionsReportOrBuilder getConnectionsOrBuilder();
}
