// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: beans.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.beans;

public interface BeanDefinitionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 scope = 1;</code>
   * @return The scope.
   */
  int getScope();

  /**
   * <code>int32 class_name = 2;</code>
   * @return The className.
   */
  int getClassName();

  /**
   * <code>int32 name = 3;</code>
   * @return The name.
   */
  int getName();

  /**
   * <code>int32 primary = 4;</code>
   * @return The primary.
   */
  int getPrimary();

  /**
   * <code>repeated int32 dependencies = 5;</code>
   * @return A list containing the dependencies.
   */
  java.util.List<java.lang.Integer> getDependenciesList();
  /**
   * <code>repeated int32 dependencies = 5;</code>
   * @return The count of dependencies.
   */
  int getDependenciesCount();
  /**
   * <code>repeated int32 dependencies = 5;</code>
   * @param index The index of the element to return.
   * @return The dependencies at the given index.
   */
  int getDependencies(int index);

  /**
   * <code>int32 stereotype = 6;</code>
   * @return The stereotype.
   */
  int getStereotype();

  /**
   * <code>bool generated = 7;</code>
   * @return The generated.
   */
  boolean getGenerated();
}
