// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: beans.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.beans;

public final class Beans {
  private Beans() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Beans.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanInitialized_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanInitialized_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinitionList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinitionList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_BeanDefinitionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_BeanDefinitionsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013beans.proto\022/io.github.sibmaks.spring." +
      "jfr.dto.protobuf.beans\"\217\001\n\016BeanDefinitio" +
      "n\022\r\n\005scope\030\001 \001(\003\022\022\n\nclass_name\030\002 \001(\003\022\014\n\004" +
      "name\030\003 \001(\003\022\017\n\007primary\030\004 \001(\003\022\024\n\014dependenc" +
      "ies\030\005 \003(\003\022\022\n\nstereotype\030\006 \001(\003\022\021\n\tgenerat" +
      "ed\030\007 \001(\005\"\274\001\n\017BeanInitialized\022\022\n\ncontext_" +
      "id\030\001 \001(\003\022\021\n\tbean_name\030\002 \001(\003\022\037\n\022pre_initi" +
      "alized_at\030\003 \001(\003H\000\210\001\001\022 \n\023post_initialized" +
      "_at\030\004 \001(\003H\001\210\001\001\022\020\n\010duration\030\005 \001(\001B\025\n\023_pre" +
      "_initialized_atB\026\n\024_post_initialized_at\"" +
      "o\n\022BeanDefinitionList\022Y\n\020bean_definition" +
      "s\030\001 \003(\0132?.io.github.sibmaks.spring.jfr.d" +
      "to.protobuf.beans.BeanDefinition\"\310\002\n\013Bea" +
      "nsReport\022k\n\020bean_definitions\030\001 \003(\0132Q.io." +
      "github.sibmaks.spring.jfr.dto.protobuf.b" +
      "eans.BeansReport.BeanDefinitionsEntry\022O\n" +
      "\005beans\030\002 \003(\0132@.io.github.sibmaks.spring." +
      "jfr.dto.protobuf.beans.BeanInitialized\032{" +
      "\n\024BeanDefinitionsEntry\022\013\n\003key\030\001 \001(\003\022R\n\005v" +
      "alue\030\002 \001(\0132C.io.github.sibmaks.spring.jf" +
      "r.dto.protobuf.beans.BeanDefinitionList:" +
      "\0028\001B3\n/io.github.sibmaks.spring.jfr.dto." +
      "protobuf.beansP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_descriptor,
        new java.lang.String[] { "Scope", "ClassName", "Name", "Primary", "Dependencies", "Stereotype", "Generated", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanInitialized_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanInitialized_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanInitialized_descriptor,
        new java.lang.String[] { "ContextId", "BeanName", "PreInitializedAt", "PostInitializedAt", "Duration", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinitionList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinitionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinitionList_descriptor,
        new java.lang.String[] { "BeanDefinitions", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_descriptor,
        new java.lang.String[] { "BeanDefinitions", "Beans", });
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_BeanDefinitionsEntry_descriptor =
      internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_descriptor.getNestedTypes().get(0);
    internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_BeanDefinitionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeansReport_BeanDefinitionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
