// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: beans.proto
// Protobuf Java Version: 4.29.3

package io.github.sibmaks.spring.jfr.dto.protobuf.beans;

/**
 * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition}
 */
public final class BeanDefinition extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition)
    BeanDefinitionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      BeanDefinition.class.getName());
  }
  // Use BeanDefinition.newBuilder() to construct.
  private BeanDefinition(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BeanDefinition() {
    dependencies_ = emptyLongList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.beans.Beans.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.sibmaks.spring.jfr.dto.protobuf.beans.Beans.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition.class, io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition.Builder.class);
  }

  public static final int SCOPE_FIELD_NUMBER = 1;
  private long scope_ = 0L;
  /**
   * <code>int64 scope = 1;</code>
   * @return The scope.
   */
  @java.lang.Override
  public long getScope() {
    return scope_;
  }

  public static final int CLASS_NAME_FIELD_NUMBER = 2;
  private long className_ = 0L;
  /**
   * <code>int64 class_name = 2;</code>
   * @return The className.
   */
  @java.lang.Override
  public long getClassName() {
    return className_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private long name_ = 0L;
  /**
   * <code>int64 name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public long getName() {
    return name_;
  }

  public static final int PRIMARY_FIELD_NUMBER = 4;
  private long primary_ = 0L;
  /**
   * <code>int64 primary = 4;</code>
   * @return The primary.
   */
  @java.lang.Override
  public long getPrimary() {
    return primary_;
  }

  public static final int DEPENDENCIES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList dependencies_ =
      emptyLongList();
  /**
   * <code>repeated int64 dependencies = 5;</code>
   * @return A list containing the dependencies.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getDependenciesList() {
    return dependencies_;
  }
  /**
   * <code>repeated int64 dependencies = 5;</code>
   * @return The count of dependencies.
   */
  public int getDependenciesCount() {
    return dependencies_.size();
  }
  /**
   * <code>repeated int64 dependencies = 5;</code>
   * @param index The index of the element to return.
   * @return The dependencies at the given index.
   */
  public long getDependencies(int index) {
    return dependencies_.getLong(index);
  }
  private int dependenciesMemoizedSerializedSize = -1;

  public static final int STEREOTYPE_FIELD_NUMBER = 6;
  private long stereotype_ = 0L;
  /**
   * <code>int64 stereotype = 6;</code>
   * @return The stereotype.
   */
  @java.lang.Override
  public long getStereotype() {
    return stereotype_;
  }

  public static final int GENERATED_FIELD_NUMBER = 7;
  private int generated_ = 0;
  /**
   * <code>int32 generated = 7;</code>
   * @return The generated.
   */
  @java.lang.Override
  public int getGenerated() {
    return generated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (scope_ != 0L) {
      output.writeInt64(1, scope_);
    }
    if (className_ != 0L) {
      output.writeInt64(2, className_);
    }
    if (name_ != 0L) {
      output.writeInt64(3, name_);
    }
    if (primary_ != 0L) {
      output.writeInt64(4, primary_);
    }
    if (getDependenciesList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(dependenciesMemoizedSerializedSize);
    }
    for (int i = 0; i < dependencies_.size(); i++) {
      output.writeInt64NoTag(dependencies_.getLong(i));
    }
    if (stereotype_ != 0L) {
      output.writeInt64(6, stereotype_);
    }
    if (generated_ != 0) {
      output.writeInt32(7, generated_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scope_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, scope_);
    }
    if (className_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, className_);
    }
    if (name_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, name_);
    }
    if (primary_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, primary_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < dependencies_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(dependencies_.getLong(i));
      }
      size += dataSize;
      if (!getDependenciesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      dependenciesMemoizedSerializedSize = dataSize;
    }
    if (stereotype_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, stereotype_);
    }
    if (generated_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, generated_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition)) {
      return super.equals(obj);
    }
    io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition other = (io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition) obj;

    if (getScope()
        != other.getScope()) return false;
    if (getClassName()
        != other.getClassName()) return false;
    if (getName()
        != other.getName()) return false;
    if (getPrimary()
        != other.getPrimary()) return false;
    if (!getDependenciesList()
        .equals(other.getDependenciesList())) return false;
    if (getStereotype()
        != other.getStereotype()) return false;
    if (getGenerated()
        != other.getGenerated()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCOPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getScope());
    hash = (37 * hash) + CLASS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getClassName());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getName());
    hash = (37 * hash) + PRIMARY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrimary());
    if (getDependenciesCount() > 0) {
      hash = (37 * hash) + DEPENDENCIES_FIELD_NUMBER;
      hash = (53 * hash) + getDependenciesList().hashCode();
    }
    hash = (37 * hash) + STEREOTYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStereotype());
    hash = (37 * hash) + GENERATED_FIELD_NUMBER;
    hash = (53 * hash) + getGenerated();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition)
      io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinitionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.beans.Beans.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.beans.Beans.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition.class, io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition.Builder.class);
    }

    // Construct using io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      scope_ = 0L;
      className_ = 0L;
      name_ = 0L;
      primary_ = 0L;
      dependencies_ = emptyLongList();
      stereotype_ = 0L;
      generated_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.beans.Beans.internal_static_io_github_sibmaks_spring_jfr_dto_protobuf_beans_BeanDefinition_descriptor;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition getDefaultInstanceForType() {
      return io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition build() {
      io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition buildPartial() {
      io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition result = new io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.scope_ = scope_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.className_ = className_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.primary_ = primary_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        dependencies_.makeImmutable();
        result.dependencies_ = dependencies_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.stereotype_ = stereotype_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.generated_ = generated_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition) {
        return mergeFrom((io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition other) {
      if (other == io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition.getDefaultInstance()) return this;
      if (other.getScope() != 0L) {
        setScope(other.getScope());
      }
      if (other.getClassName() != 0L) {
        setClassName(other.getClassName());
      }
      if (other.getName() != 0L) {
        setName(other.getName());
      }
      if (other.getPrimary() != 0L) {
        setPrimary(other.getPrimary());
      }
      if (!other.dependencies_.isEmpty()) {
        if (dependencies_.isEmpty()) {
          dependencies_ = other.dependencies_;
          dependencies_.makeImmutable();
          bitField0_ |= 0x00000010;
        } else {
          ensureDependenciesIsMutable();
          dependencies_.addAll(other.dependencies_);
        }
        onChanged();
      }
      if (other.getStereotype() != 0L) {
        setStereotype(other.getStereotype());
      }
      if (other.getGenerated() != 0) {
        setGenerated(other.getGenerated());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              scope_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              className_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              name_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              primary_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              long v = input.readInt64();
              ensureDependenciesIsMutable();
              dependencies_.addLong(v);
              break;
            } // case 40
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureDependenciesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                dependencies_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 42
            case 48: {
              stereotype_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              generated_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long scope_ ;
    /**
     * <code>int64 scope = 1;</code>
     * @return The scope.
     */
    @java.lang.Override
    public long getScope() {
      return scope_;
    }
    /**
     * <code>int64 scope = 1;</code>
     * @param value The scope to set.
     * @return This builder for chaining.
     */
    public Builder setScope(long value) {

      scope_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 scope = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScope() {
      bitField0_ = (bitField0_ & ~0x00000001);
      scope_ = 0L;
      onChanged();
      return this;
    }

    private long className_ ;
    /**
     * <code>int64 class_name = 2;</code>
     * @return The className.
     */
    @java.lang.Override
    public long getClassName() {
      return className_;
    }
    /**
     * <code>int64 class_name = 2;</code>
     * @param value The className to set.
     * @return This builder for chaining.
     */
    public Builder setClassName(long value) {

      className_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 class_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      className_ = 0L;
      onChanged();
      return this;
    }

    private long name_ ;
    /**
     * <code>int64 name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public long getName() {
      return name_;
    }
    /**
     * <code>int64 name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(long value) {

      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      name_ = 0L;
      onChanged();
      return this;
    }

    private long primary_ ;
    /**
     * <code>int64 primary = 4;</code>
     * @return The primary.
     */
    @java.lang.Override
    public long getPrimary() {
      return primary_;
    }
    /**
     * <code>int64 primary = 4;</code>
     * @param value The primary to set.
     * @return This builder for chaining.
     */
    public Builder setPrimary(long value) {

      primary_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 primary = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrimary() {
      bitField0_ = (bitField0_ & ~0x00000008);
      primary_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList dependencies_ = emptyLongList();
    private void ensureDependenciesIsMutable() {
      if (!dependencies_.isModifiable()) {
        dependencies_ = makeMutableCopy(dependencies_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated int64 dependencies = 5;</code>
     * @return A list containing the dependencies.
     */
    public java.util.List<java.lang.Long>
        getDependenciesList() {
      dependencies_.makeImmutable();
      return dependencies_;
    }
    /**
     * <code>repeated int64 dependencies = 5;</code>
     * @return The count of dependencies.
     */
    public int getDependenciesCount() {
      return dependencies_.size();
    }
    /**
     * <code>repeated int64 dependencies = 5;</code>
     * @param index The index of the element to return.
     * @return The dependencies at the given index.
     */
    public long getDependencies(int index) {
      return dependencies_.getLong(index);
    }
    /**
     * <code>repeated int64 dependencies = 5;</code>
     * @param index The index to set the value at.
     * @param value The dependencies to set.
     * @return This builder for chaining.
     */
    public Builder setDependencies(
        int index, long value) {

      ensureDependenciesIsMutable();
      dependencies_.setLong(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 dependencies = 5;</code>
     * @param value The dependencies to add.
     * @return This builder for chaining.
     */
    public Builder addDependencies(long value) {

      ensureDependenciesIsMutable();
      dependencies_.addLong(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 dependencies = 5;</code>
     * @param values The dependencies to add.
     * @return This builder for chaining.
     */
    public Builder addAllDependencies(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureDependenciesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, dependencies_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 dependencies = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDependencies() {
      dependencies_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private long stereotype_ ;
    /**
     * <code>int64 stereotype = 6;</code>
     * @return The stereotype.
     */
    @java.lang.Override
    public long getStereotype() {
      return stereotype_;
    }
    /**
     * <code>int64 stereotype = 6;</code>
     * @param value The stereotype to set.
     * @return This builder for chaining.
     */
    public Builder setStereotype(long value) {

      stereotype_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 stereotype = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStereotype() {
      bitField0_ = (bitField0_ & ~0x00000020);
      stereotype_ = 0L;
      onChanged();
      return this;
    }

    private int generated_ ;
    /**
     * <code>int32 generated = 7;</code>
     * @return The generated.
     */
    @java.lang.Override
    public int getGenerated() {
      return generated_;
    }
    /**
     * <code>int32 generated = 7;</code>
     * @param value The generated to set.
     * @return This builder for chaining.
     */
    public Builder setGenerated(int value) {

      generated_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 generated = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenerated() {
      bitField0_ = (bitField0_ & ~0x00000040);
      generated_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition)
  }

  // @@protoc_insertion_point(class_scope:io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition)
  private static final io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition();
  }

  public static io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BeanDefinition>
      PARSER = new com.google.protobuf.AbstractParser<BeanDefinition>() {
    @java.lang.Override
    public BeanDefinition parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BeanDefinition> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BeanDefinition> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.sibmaks.spring.jfr.dto.protobuf.beans.BeanDefinition getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

